---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - replication.storage.openshift.io
  resources:
  - volumegroupreplicationclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - replication.storage.openshift.io
  resources:
  - volumegroupreplicationclasses/finalizers
  verbs:
  - update
- apiGroups:
  - replication.storage.openshift.io
  resources:
  - volumegroupreplicationclasses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - replication.storage.openshift.io
  resources:
  - volumegroupreplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - replication.storage.openshift.io
  resources:
  - volumegroupreplications/finalizers
  verbs:
  - update
- apiGroups:
  - replication.storage.openshift.io
  resources:
  - volumegroupreplications/status
  verbs:
  - get
  - patch
  - update
