# permissions for end users to edit volumegroupreplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volumegroupreplication-editor-role
rules:
- apiGroups:
  - replication.storage.openshift.io
  resources:
  - volumegroupreplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - replication.storage.openshift.io
  resources:
  - volumegroupreplications/status
  verbs:
  - get
