# permissions for end users to view volumegroupreplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volumegroupreplication-viewer-role
rules:
- apiGroups:
  - replication.storage.openshift.io
  resources:
  - volumegroupreplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - replication.storage.openshift.io
  resources:
  - volumegroupreplications/status
  verbs:
  - get
