# permissions for end users to view volumegroupreplicationclasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volumegroupreplicationclass-viewer-role
rules:
- apiGroups:
  - replication.storage.openshift.io
  resources:
  - volumegroupreplicationclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - replication.storage.openshift.io
  resources:
  - volumegroupreplicationclasses/status
  verbs:
  - get
