apiVersion: replication.storage.openshift.io/v1alpha1
kind: VolumeGroupReplicationClass
metadata:
  labels:
    app.kubernetes.io/name: volumegroupreplicationclass
    app.kubernetes.io/instance: volumegroupreplicationclass-sample
    app.kubernetes.io/part-of: kubernetes-csi-addons
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubernetes-csi-addons
  name: volumegroupreplicationclass-sample
spec:
  provisioner: driver.csi.com
  parameters:
    replication.storage.openshift.io/group-replication-secret-name: secret
    replication.storage.openshift.io/group-replication-secret-namespace: default
