apiVersion: replication.storage.openshift.io/v1alpha1
kind: VolumeGroupReplication
metadata:
  labels:
    app.kubernetes.io/name: volumegroupreplication
    app.kubernetes.io/instance: volumegroupreplication-sample
    app.kubernetes.io/part-of: kubernetes-csi-addons
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubernetes-csi-addons
  name: volumegroupreplication-sample
spec:
  source:
    selector:
      matchLabels:
        group: replication
  volumeGroupReplicationClassName: volumegroupreplicationclassname
  replicationState: primary
