apiVersion: replication.storage.openshift.io/v1alpha1
kind: VolumeGroupReplicationContent
metadata:
  labels:
    app.kubernetes.io/name: volumegroupreplicationcontent
    app.kubernetes.io/instance: volumegroupreplicationcontent-sample
    app.kubernetes.io/part-of: kubernetes-csi-addons
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubernetes-csi-addons
  name: volumegroupreplicationcontent-sample
spec:
  volumeGroupReplicationRef:
    name: volumegroupreplication
    namespace: default
  volumeGroupReplicationHandle: replicationHandle
  provisioner: driver.csi.com
  volumeGroupReplicationClassName: volumegroupreplicationclassname
  source:
    - volumeHandles: volumeID
